# Generated by Django 4.1.5 on 2023-01-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TruFit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfuser',
            name='active_role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('SalesEngineer', 'SalesEngineer'), ('AccountManager', 'AccountManager')], default='SalesEngineer', max_length=20),
        ),
        migrations.AlterField(
            model_name='tfuser',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('SalesEngineer', 'SalesEngineer'), ('AccountManager', 'AccountManager')], default='Admin', max_length=20),
        ),
    ]
